name: Build and Zip Chrome Extension

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Extract version from package.json
        id: extract_version
        run: echo "::set-output name=version::$(node -p 'require("./package.json").version')"

      - name: Install dependencies
        run: yarn

      - name: Build Chrome
        run: yarn zip:chrome

      - name: Upload Chrome extension artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vite-web-extension-chrome-${{ steps.extract_version.outputs.version }}
          path: chrome.zip
